check if the zip file could be extracted

diff --git a/bin/create-symfony2-project b/bin/create-symfony2-project
--- a/bin/create-symfony2-project
+++ b/bin/create-symfony2-project
@@ -111,6 +111,10 @@ fi
 
 # extract zip
 unzip $DIR/../downloads/$filename
+if [ "$?" ==  1 ]; then
+    echo "Cannot extract $DIR/../downloads/$filename"
+    exit 1
+fi
 
 # check if the folder within zip exists
 if [ ! -d $foldername ]; then
